{{- $fullName := include "chart-12factor.fullname" . -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "chart-12factor.labels" . | nindent 4 }}
spec:
  rules:
    - host: {{ .Release.Name }}.{{ .Release.Namespace }}.{{ default "k8z.eu" .Values.tld }}
      http:
        paths:
        - backend:
            service:
              name: {{ $fullName }}
              port:
                number: 80
          path: /
          pathType: ImplementationSpecific
